packages:
  - packages/*

allowBuilds:
  esbuild: true

catalog:
  '@clack/prompts': ^1.8.1
  '@types/node': ^24.19.1
  esbuild: ^0.28.2
  rstack: ^0.8.1
  tar: ^7.5.22
  vite: ^8.3.4
  yaml: ^2.9.1

catalogs:
  peers:
    '@rsbuild/core': '>=1.4.8 <3'
    vite: '>=6 <9'
